Inputs:
    - j1_ptrel
    - j1_etarot
    - j1_phirot
    - j1_erel
    - j1_deltaR
    - j1_pdgid
    - j_pt
    
Labels:
    - j_g
    - j_q
    - j_w
    - j_z
    - j_t
    - j_pt
    
KerasModel: lstm_model
KerasModelRetrain: lstm_model_constraint
KerasLoss: categorical_crossentropy
L1Reg: 0.0001
L1RegR: 0.001
NormalizeInputs: 1
InputType: Conv1D
MaxParticles: 20
